# WARNING - Generated by {fusen} from /dev/ridlle_dev.Rmd: do not edit by hand

test_that("ridl works", {   
  expect_true(inherits(ridl, "function")) 
  ## GPT unit test
  #expect_equal(ridl(action = "test"), "test")
 # expect_error(ridl(action = "invalid"), "Invalid action: invalid")
  })
