# WARNING - Generated by {fusen} from /dev/ridlle_dev.Rmd: do not edit by hand

test_that("resource works", { 
  expect_true(inherits(resource_create, "function")) 
  expect_true(inherits(resource_update, "function")) 
  expect_true(inherits(resource_patch, "function")) 
  expect_true(inherits(resource_delete, "function")) 
  expect_true(inherits(resource_search, "function")) 
  
  })
