# WARNING - Generated by {fusen} from /dev/ridlle_dev.Rmd: do not edit by hand

#' container_show  
#' 
#' Get an overview of accessible infos about all containers in RIDL
#'  Use https://docs.ckan.org/en/2.9/api/index.html#ckan.logic.action.get.organization_show  
#' @param id id or name of the container
#' @return a dataframe with container metadata
#' 
#' @export
#' @examples
#' # americasdataset <- container_show( id = "americas-regional-dataset")
container_show <- function(id) {
      ridl(action ="organization_show",
           include_datasets = TRUE,
           id = id)-> r
    r$result %>% 
    dataset_tibblify() -> res
}
