# WARNING - Generated by {fusen} from /dev/ridlle_dev.Rmd: do not edit by hand

#' container_list
#' 
#' Provide a list of all child containers for a specific container
#' 
#' This function is used to generate a regional dashbaord..
#' Be carefull - it's an expansive functions at it needs to parse the entire 
#' content of the server.... 
#' 
#' uses https://docs.ckan.org/en/2.9/api/index.html#ckan.logic.action.get.organization_list
#' @param parent name of the container
#' @return catalog of containers
#' 
#' @importFrom tibble as_tibble
#' @importFrom tidyr unnest_wider
#' @importFrom purrr map list_rbind
#' 
#' @export
#' @examples
#' # catalog <- container_list()
#' # groups_name <- catalog |>
#' #                   dplyr::select(groups_name) |>
#' #                   dplyr::distinct()
#' 
container_list <- function(parent) {
    
    ## First we list all the containers in the server
    container_get <- function() {
      ridl(action ="organization_list",
           type = "data-container" ) -> r
      r$result  |> length() -> res
    
      return(res)  }
    cont <- container_get()
    
    ## Now we build the full catalog 
    catalog <-
      purrr::map(seq(0, cont, by = 25),
          \(x) ridl(action ="organization_list",
                    type = "data-container",
                    offset = x,
                    all_fields = TRUE,
                    include_groups = TRUE)  %>% .[["result"]]) |>
      purrr::list_rbind() |>
      tidyr::unnest_wider(groups, names_sep = "_") |>
      tibble::as_tibble()
    
    return(catalog)
}
 
