# WARNING - Generated by {fusen} from /dev/ridlle_dev.Rmd: do not edit by hand

#' find_child_containers
#' 
#' Provide a list of all child containers - including nested one - for a specific container
#' 
#' Be carefull - it's an expansive functions at it needs to parse the entire 
#' content of the server.... 
#' 
#' @param parent name of the parent container
#' @param catalog daaframe object with a catalog of container produced by container_list()
#' 
#' @return vector with all child container
#' 
#' @importFrom dplyr filter
#' @importFrom rlang is_empty
#' @importFrom purrr map
#' 
#' @export
#' @examples
#' #catalog <- container_list()
#' # containerAmericas <- find_child_containers(parent = "americas",
#' #                                            catalog = catalog)
find_child_containers <- function(parent, catalog ) {
   # catalog <- container_list()
    
    find_child_containers2 <- function(parent) {
    ## Now we filter the catalog only for the children of the desired container
      children <- dplyr::filter(catalog, groups_name == parent)$name
      if (rlang::is_empty(children))
        return(NULL)
      c(children, unlist(purrr::map(children, find_child_containers2))) }
    
   result <-  find_child_containers2(parent)

}

