# WARNING - Generated by {fusen} from /dev/ridlle_dev.Rmd: do not edit by hand

#' Fetch resource from RIDL
#' @param url The URL of the resource to fetch
#' @param path Location to store the resource
#'             
#' @importFrom httr GET add_headers write_disk
#'
#' @return Path to the downloaded file
#' @export
#' @examples
#' 
#' ## Example 1: with a direct URL
#' #-----
#' # Test search in prod
#' # Sys.unsetenv("USE_UAT")
#' 
#' 
#' # resource_fetch(url = 'https://ridl.unhcr.org/dataset/a60f4b79-8acc-4893-8fb9-d52f94416b19/resource/daa2b9e4-bf97-4302-86a5-08bb62a5a937/download/df_age_2022.csv',
#' # path = tempfile())
#' 
#' 
#' ## Example 2: Let's try to identify a resource - then fetch it locally and update it back... as from here
#' # https://github.com/unhcr-americas/darien_gap_human_mobility/blob/main/report.Rmd#L38
#' # Sys.unsetenv("USE_UAT")
#' # ## Get the dataset metadata based on its canonical name
#' # p <- riddle::dataset_show('rms_v4')
#' # ## Let's get the fifth resource within this dataset
#' # test_ressources <- p[["resources"]][[1]] |> dplyr::slice(5)
#' #
#' # ## Download the resource locally in a file name file..
#' # resource_fetch(url = test_ressources$url,   path =  here::here("file"))
#' # test_ressources$url
#' # # Rebuild the metadata
#' # m <- resource_metadata(type = test_ressources$type, #"data",
#' #                          url = "df_gender_2020.csv",
#' # upload = httr::upload_file(here::here("file")),
#'  #                          name = test_ressources$name, 
#' # "Irregular entries by gender in 2022",
#' #                          format = test_ressources$format, #"csv",
#' #                          file_type =  test_ressources$file_type, #"microdata",
#' #                          visibility = test_ressources$visibility, # "public",
#' #                          date_range_start =  test_ressources$date_range_start,
#' # "2022-01-01",
#' #                          date_range_end = test_ressources$date_range_end, #as.character(floor_date(today('America/Panama'), "month") - days(1)), 
#' #end day of last month
#' #                          version = test_ressources$version, # "0",
#' #                          process_status = test_ressources$process_status, 
#' #"anonymized",
#' #                          identifiability = test_ressources$identifiability, #"anonymized_public"
#' #   )
#' 
#' 
#' #r <- resource_update(id = test_ressources$id,  res_metadata = m)
#'  
#' 
#' 
#' 
#' 
#' 
resource_fetch <- function(url, 
                           path = tempfile()) {
  
  ## Remove file if it exist..
  if (file.exists(path)) file.remove(path)
  
 if(Sys.getenv("USE_UAT")==1)   {
    httr::GET(url,
            httr::add_headers("X-CKAN-API-Key" = Sys.getenv("RIDL_UAT_API_TOKEN")),
            httr::write_disk(path)) 
 }
  else  {
    httr::GET(url,
            httr::add_headers("X-CKAN-API-Key" = Sys.getenv("RIDL_API_TOKEN")),
            httr::write_disk(path))    }
  return(path)
}
