# WARNING - Generated by {fusen} from /dev/ridlle_dev.Rmd: do not edit by hand

#' resource_tibblify
#' 
#' Helper function to package API results as a  tibble
#' 
#' @param x list 
#' @return list tiblified
#' @importFrom purrr modify_if  
#' @importFrom rlang is_empty  
#' @importFrom tibble as_tibble
#' 
#' @export
# 
#' @examples
#' m <- riddle::resource_metadata(type = "data",
#'                        url = "mtcars.csv",
#'  # upload = httr::upload_file(system.file("extdata/mtcars.csv", package = "readr")),
#'                        name = "mtcars.csv",
#'                        format = "csv",
#'                        file_type = "microdata",
#'                        date_range_start = "1973-01-01",
#'                        date_range_end = "1973-12-31",
#'                        version = "1",
#'                        visibility = "public",
#'                        process_status = "raw",
#'                        identifiability = "anonymized_public")
#' 
#' m1 <- riddle::resource_tibblify(m)
#' 
#' 
#' 
#' m1
resource_tibblify <- function(x) {
  x %>% purrr::modify_if(rlang::is_empty, ~NA) %>% tibble::as_tibble()
}
