# WARNING - Generated by {fusen} from /dev/ridlle_dev.Rmd: do not edit by hand

#' Convenience function to record resource metadata
#'
#' @description This functions create the resource metadata
#' 
#'
#' @details All arguments are of type character.
#'
#' Fields marked with a (*) are required for \code{\link{resource_create()}} and \code{\link{resource_update()}} operations.
#' @param type Resource type(*) - The kind of file you want to upload. Allowed values: `data` (Data file), `attachment` (Additional attachment).
#' @param url Upload - The file name as it will be recorded in the system.
#' @param name Name - eg. January 2011 Gold Prices.
#' @param description Description - Some usefule notes about the data.
#' @param format File format - eg. CSV, XML, or JSON.
#' @param file_type File type(*) - Indicates what is contained in the file. Allowed values: `microdata` (Microdata), `questionnaire` (Questionnaire), `report` (Report), `sampling_methodology` (Sampling strategy & methodology Description), `infographics` (Infographics & Dashboard), `script` (Script), `concept note` (Concept Note), `other` (Other).
#' @param `hxl-ated` HXL-ated.
#' @param date_range_start Data collection first date(*) - Use yyyy-mm-dd format.
#' @param date_range_end Data collection last date(*) - Use yyyy-mm-dd format.
#' @param upload File to upload. Passed using `httr::upload_file()`.
#' @param visibility should be either
#' @param version Version(*).
#' @param `hxl-ated` HXL-ated. Allowed values: `False` (No), `True` (Yes).
#' @param process_status File process status(*) - Indicates the processing stage of the data. 'Raw' means that the data has not been cleaned since collection. 'In process' means that it is being cleaned. 'Final' means that the dataset is final and ready for use in analytical products. Allowed valued: `raw` (Raw-Uncleaned), `cleaned` (Cleaned Only), `anonymized` (Cleaned & Anonymized).
#' @param identifiability Identifiability(*) - Indicates if personally identifiable data is contained in the dataset. Allowed values: `personally_identifiable` (Personally identifiable), `anonymized_enclave` (Anonymized 1st level: Data Enclave - only removed direct identifiers), `anonymized_scientific` (Anonymized 2st level: Scientific Use File (SUF)), `anonymized_public` (Anonymized 3st level: Public Use File (PUF)).
#' @param ... ignored.
#'
#' @return A list with the provided metadata.
#' @export

#' @examples
#' #resource_metadata()
#' m <- riddle::resource_metadata(type = "data",
#'                        url = "mtcars.csv",
#'                        name = "mtcars.csv",
#'                        format = "csv",
#'                        file_type = "microdata",
#'                        date_range_start = "1973-01-01",
#'                        date_range_end = "1973-12-31",
#'                        version = "1",
#'                        visibility = "public",
#'                        process_status = "raw",
#'                        identifiability = "anonymized_public")
#' m
resource_metadata <- function(type = NULL,
                              url = NULL,
                              name = NULL,
                              description = NULL,
                              format = NULL,
                              file_type = NULL,
                              date_range_start = NULL,
                              date_range_end = NULL,
                              upload = NULL,
                              visibility = NULL,
                              version = NULL,
                              `hxl-ated` = NULL,
                              process_status = NULL,
                              identifiability = NULL,
                              ...) {
  list(type = type,
       url = url,
       name = name,
       description = description,
       format = format,
       file_type = file_type,
       date_range_start = date_range_start,
       date_range_end = date_range_end,
       upload = upload,
       visibility = visibility,
       version = version,
       `hxl-ated` = `hxl-ated`,
       process_status = process_status,
       identifiability = identifiability) %>%
    purrr::discard(purrr::is_empty)
}


