# WARNING - Generated by {fusen} from /dev/ridlle_dev.Rmd: do not edit by hand

#' 
#' Work with RIDL resources (files)
#' 
#' @name resource
#'
#' @details You must have the necessary permissions to create, edit, or delete 
#'          datasets and their resources.
#'
#' Note that several fields are required for `resource_create()` and 
#' `resource_update()` operations to succeed. 
#'   Consult \code{\link{resource_metadata()}} for the details.
#'
#' For `resource_update()`/`resource_patch()` operations, it is recommended to 
#' call `resource_show()`, make the desired changes to the result, and then 
#' call `resource_update()`/`resource_patch()` with it.
#'
#' The difference between the update and patch methods is that the patch will 
#' perform an update of the provided parameters, while leaving all other 
#' parameters unchanged, whereas the update methods deletes all parameters
#'  not explicitly provided in the `metadata`.
#'
#' @param res_metadata Metadata created by \code{\link{resource_metadata()}}.
#' @param id The id or name of the resource.
#' @param dataset_id The id or name of the dataset to which this resource belongs to.
#' 
#' @importFrom httr upload_file
#'
#' @return The resource.
#' @rdname resource
#' @export
#' @examples
#' ## let's get again the details of the dataset we want to add the resource in..
#' #-----
#' # Test search in prod
#' Sys.unsetenv("USE_UAT")
#' p <- riddle::dataset_search("rms_v4")
#' p
#' 
#' #-----
#' # Test search in uat
#' Sys.setenv(USE_UAT=1)
#' p <- riddle::dataset_search("tests")
#' p
#' ##take the first one
#' ridlid <- as.character(p[9, c("id")])
#' 
#' ## let's get again the details of the dataset we want to add the resource in..
#' #r <- riddle::resource_create(dataset_id = ridlid, res_metadata = m)
#' # Like before, the return value is a tibble representation of the resource.
#' #r
#'  
#' ## and now can search for it - checking it is correctly there... 
#' ##riddle::resource_search("name:mtcarsriddle")
#' 
#' # And once we’re done experimenting with the API, we should take down our
#' # toy dataset since we don’t really need it on RIDL.
#' #riddle::dataset_delete(p$id)
#' 
#' 
#' #-----
#' # Test search in prod
#' Sys.unsetenv("USE_UAT")
#' p <- riddle::dataset_show('rms_v4')
#' dataset_id_rms <- p$id
#' list_of_ressources <- p[["resources"]][[1]]
#' knitr::kable(list_of_ressources)
#' 
#' new_attachment <- riddle::resource_metadata(type = "attachment",
#'                        url = "resource.R", 
#' # upload = httr::upload_file(here::here("R","resource.R") ),
#' ## # Error:
#' # ! All columns in a tibble must be vectors.
#' # ✖ Column `upload` is a `form_file` object.
#'                        name = "Rscript",
#'                        format = "R",
#'                        file_type = "report",
#'                        version = "1",
#'                        visibility = "public" )
#' 
#' ## Now testing adding the file "resource.R" as an attachment in the 
#' ## dataset 'rms_v4'
#' 
#' # but not working.... 
#' # resource_create(dataset_id = dataset_id_rms, 
#' #                         res_metadata = new_attachment )
#' # Error in ridl(action = "resource_create", dataset_id = dataset_id, !!!res_metadata, : 
#' # __type: Not Found Error
#' # message: Not found: No dataset id provided, cannot check auth.
#' 
#' m <- riddle::resource_metadata(type = "data",
#'                        url = "mtcars.csv",
#' #  upload = httr::upload_file(system.file("extdata/mtcars.csv", package = "readr")),         
#' ## # Error:
#' # ! All columns in a tibble must be vectors.
#' # ✖ Column `upload` is a `form_file` object.
#'                        name = "mtcars.csv",
#'                        format = "csv",
#'                        file_type = "microdata",
#'                        date_range_start = "1973-01-01",
#'                        date_range_end = "1973-12-31",
#'                        version = "1",
#'                        visibility = "public",
#'                        process_status = "raw",
#'                        identifiability = "anonymized_public")
#' # same pb... 
#' # resource_create(dataset_id = dataset_id_rms, 
#' #                          res_metadata = m )
#' # Error in ridl(action = "resource_create", dataset_id = dataset_id, !!!res_metadata, : 
#' # __type: Not Found Error
#' # message: Not found: No dataset id provided, cannot check auth.
#' 
resource_create <- function(dataset_id, res_metadata) {
  enc <- if(is.null(res_metadata$upload)) "json" else "multipart"
  ridl(action ="resource_create", 
       dataset_id = dataset_id,
       !!!res_metadata,
       .encoding = enc) %>% 
    resource_tibblify()
}


#' @rdname search
#' @export
resource_search <- function(query = NULL,
                            rows = NULL, 
                            start = NULL) {
  ridl(action ="resource_search",
       !!!(as.list(match.call()[-1])))$results %>% 
    tibble::as_tibble()
}
  


#' @rdname resource
#' @export
resource_update <- function(id, res_metadata) {
  enc <- if(is.null(res_metadata$upload)) "json" else "multipart"
  ridl(action ="resource_update",
       id = id,
       !!!res_metadata,
       .encoding = enc) %>% 
    resource_tibblify()
}

#' @rdname resource
#' @export
resource_patch <- function(id, res_metadata) {
  enc <- if(is.null(res_metadata$upload)) "json" else "multipart"
  ridl(action ="resource_patch",
       id = id,
       !!!res_metadata, 
       .encoding = enc) %>% 
    resource_tibblify()
}

#' @rdname resource
#' @export
resource_delete <- function(id) { 
  ridl(action ="resource_delete",
       id = id) }


