# WARNING - Generated by {fusen} from /dev/ridlle_dev.Rmd: do not edit by hand

#' apihelper
#' 
#' Helper function to make API calls
#'
#' @param action Operation to execute. See [CKAN's API documentation](https://docs.ckan.org/en/2.9/api/) for details.
#' @param uat Boolean TRUE /FALSE tells whether to use https://ridl-uat.unhcr.org/ or https://ridl.unhcr.org/.
#'             FALSE per default
#' @param .encoding HTTP POST encoding to use - one of `json`, `form`, or `multipart`.
#' @importFrom httr POST
#'
#'
#' @return `httr::response` object with the result of the call.
#' @export
#' @examples
#' # ridl()
ridl <- function(action, ...,
                 .encoding = "json",
                 uat = FALSE) {
  if(uat == TRUE)  {
    baseurl <- "https://ridl-uat.unhcr.org/"
    r <- httr::POST(baseurl,
               path = glue::glue("/api/action/{action}"),
               httr::add_headers("Authorization" = Sys.getenv("RIDL_API_KEY_UAT")),
               body = rlang::list2(...),
               encode = .encoding) %>%
          httr::content(simplifyVector = TRUE) 
    } else {
    baseurl <- "https://ridl.unhcr.org/"
    r <- httr::POST(baseurl,
               path = glue::glue("/api/action/{action}"),
               httr::add_headers("Authorization" = Sys.getenv("RIDL_API_KEY")),
               body = rlang::list2(...),
               encode = .encoding) %>%
          httr::content(simplifyVector = TRUE) }

  if (!r$success)
    stop(r$error %>%
           purrr::imap(~glue::glue("{.y}: {.x}")) %>%
           unlist() %>%
           stringr::str_c(collapse = "\n"))

  r$result
}


