# WARNING - Generated by {fusen} from /dev/ridlle_dev.Rmd: do not edit by hand

#' apihelper
#' 
#' Helper function to make [API calls](https://docs.ckan.org/en/2.9/api/index.html#action-api-reference).
#'  Calls includes the 10 following actions:
#' 
#' On dataset
#'  * "package_create"
#'  * "package_update"
#'  * "package_patch"
#'  * "package_delete"
#'  * "package_search"
#'  
#' On resource  
#'  * "resource_create"
#'  * "resource_update"
#'  * "resource_patch"
#'  * "resource_delete"
#'  * "resource_search"
#'
#' The package works with both the production and UAT instances of RIDL. 
#' To use the UAT version, run `Sys.setenv(USE_UAT=1)` before calling any functions
#'  from the package.
#'  To go back to the production instance, call `Sys.unsetenv("USE_UAT")`.
#'
#'
#' @param action Operation to execute. See [CKAN's API documentation](https://docs.ckan.org/en/2.9/api/) for details.
#' @param .encoding HTTP POST encoding to use - one of `json`, `form`, or `multipart`.
#' @param ... whatever is needed
#' @param verbose TRUE FALSE to display info on the console about the API call
#' @importFrom httr POST
#'
#'
#' @return `httr::response` object with the result of the call.
#' @export

#' @examples
#' # ridl(action ="package_search", as.list("cbi"))
ridl <- function(action,
                 ...,
                 .encoding = "json",
                 verbose = FALSE) {
     # if(Sys.setenv(USE_UAT=1))  {
      if(verbose == TRUE) {print( c("Running ridl action", action))}
      

      # It's ok to check the environment using Sys.setenv()?
      # Should Sys.getenv() will be better?
      if(Sys.getenv("USE_UAT") == 1)  {
        token <- Sys.getenv("RIDL_UAT_API_TOKEN")
        if(verbose == TRUE) {print(" - env: UAT")}
        #print(" - env: UAT")
        #nchar(token) - show the end of the token as the beginning is more likely to be the same... 
        if(verbose == TRUE) {print( c(" - key", substr(token, (nchar(token)-5) , nchar(token))  ) )}
        #print( c(" - key", substr(token, (nchar(token)-5) , nchar(token))  ) )
      
        r <- httr::POST("https://ridl-uat.unhcr.org/",
                 path = glue::glue("/api/action/{action}"),
               # httr::add_headers("Authorization" = Sys.getenv("RIDL_API_KEY_UAT")),
               #  httr::add_headers("Authorization" = Sys.getenv("RIDL_UAT_API_TOKEN")),
                 httr::add_headers("X-CKAN-API-Key" = token),
                 body = rlang::list2(...),
                 encode = .encoding) %>%
            httr::content(simplifyVector = TRUE)
      
    } else    {
      
      token <- Sys.getenv("RIDL_API_TOKEN")
        if(verbose == TRUE) {print(" - env: PRODUCTION")}
        # print(" - env: PRODUCTION")
      
      #nchar(token) - show the end of the token as the beginning is more likely to be the same... 
        if(verbose == TRUE) { print( c(" - key", substr(token, (nchar(token)-5) , nchar(token))  ) )}
       #  print( c(" - key", substr(token, (nchar(token)-5) , nchar(token))  ) )
    
      r <- httr::POST("https://ridl.unhcr.org/",
                 path = glue::glue("/api/action/{action}"),
                # httr::add_headers("Authorization" = Sys.getenv("RIDL_API_KEY")),
                 # httr::add_headers("Authorization" = Sys.getenv("RIDL_API_TOKEN")),
                 httr::add_headers("X-CKAN-API-Key" = token),
                 body = rlang::list2(...),
                 encode = .encoding) %>%
            httr::content(simplifyVector = TRUE) 
      
       }
  
  ## Display results in console
    if(verbose == TRUE) {message(r$result)}
  
  ## Error catching
  if (!r$success)
    stop(r$error %>%
           purrr::imap(~glue::glue("{.y}: {.x}")) %>%
           unlist() %>%
           stringr::str_c(collapse = "\n"))
  
  ## Return all the details of the API interaction... 
  return(r)
}


