# WARNING - Generated by {fusen} from /dev/ridlle_dev.Rmd: do not edit by hand

#' apihelper
#' 
#' Helper function to make API calls. Calls includes the 10 following actions:
#' 
#'  * "package_create"
#'  * "package_update"
#'  * "package_patch"
#'  * "package_delete"
#'  * "package_search"
#'  * "resource_create"
#'  * "resource_update"
#'  * "resource_patch"
#'  * "resource_delete"
#'  * "resource_search"
#'
#' The package works with both the production and UAT instances of RIDL. 
#' To use the UAT version, run `Sys.setenv(USE_UAT=1)` before calling any functions
#'  from the package.
#'  To go back to the production instance, call `Sys.unsetenv("USE_UAT")`.
#'
#'
#' @param action Operation to execute. See [CKAN's API documentation](https://docs.ckan.org/en/2.9/api/) for details.
#' @param .encoding HTTP POST encoding to use - one of `json`, `form`, or `multipart`.
#' @importFrom httr POST
#'
#'
#' @return `httr::response` object with the result of the call.
#' @export
#' @examples
#' # ridl(action ="package_search", as.list("cbi"))
ridl <- function(action,
                 ...,
                 .encoding = "json") {
  if(Sys.setenv(USE_UAT=1))  {
      baseurl <- "https://ridl.unhcr.org/"
      r <- httr::POST(baseurl,
                 path = glue::glue("/api/action/{action}"),
                 httr::add_headers("Authorization" = Sys.getenv("RIDL_API_KEY")),
                 body = rlang::list2(...),
                 encode = .encoding) %>%
            httr::content(simplifyVector = TRUE) 
    } else {
      baseurl <- "https://ridl-uat.unhcr.org/"
      r <- httr::POST(baseurl,
                 path = glue::glue("/api/action/{action}"),
                 httr::add_headers("Authorization" = Sys.getenv("RIDL_API_KEY_UAT")),
                 body = rlang::list2(...),
                 encode = .encoding) %>%
            httr::content(simplifyVector = TRUE) }

  if (!r$success)
    stop(r$error %>%
           purrr::imap(~glue::glue("{.y}: {.x}")) %>%
           unlist() %>%
           stringr::str_c(collapse = "\n"))

  r$result
}


