# WARNING - Generated by {fusen} from /dev/ridlle_dev.Rmd: do not edit by hand



# usethis::use_rmarkdown_template(
#   template_name = "Summary_Report",
#   template_dir = NULL,
#   template_description = "Summary information of RIDL Dataset",
#   template_create_dir = TRUE
# )

#' Generate a RIDL factsheet 
#' 
#' @param container list of container to generate the factsheet to generate
#' @importFrom unhcrdown paged_simple
#' 
#' @export
#' @examples
#' # summary_report(year = 2022,
#' #                                    region = "Americas")
summary_report <- function(container = "Americas") {
  rmarkdown::render(
    system.file("rmarkdown/templates/summary_report/skeleton/skeleton.Rmd", package = "riddle"),
    output_file = here::here(paste0('StatFactsheet-', container,   '.html') ),
    params = list(container = container)  )
  }
